#!/usr/bin/env python3
"""
research-propose.py — Write a VALIDATED research proposal to the queued/ dir.

PROPOSE-only: writing a proposal changes NOTHING live. The apply path is a
separate gated step (NN#10 pipeline, driven by Jarvis at session-start
collation). This script never applies, merges, or executes any proposal.

Usage:
    python3 Meta/sync/research-propose.py \\
        --title "Add funding-rate feature to ETH strategy" \\
        --hypothesis "Funding rate sign predicts 5-min direction on ETH." \\
        --evidence "backtest WR=56% n=142" "features.py line 42 unused" \\
        --target "my-project/strategy/features.py" \\
        --risk-class trading-logic \\
        --diff "Add funding_rate as feature[15]; retrain ETH model." \\
        [--slug my-slug]          # optional; auto-derived from title if omitted
        [--queue-dir /path/to/dir]  # default: Meta/research-proposals/queued/

    python3 Meta/sync/research-propose.py --demo
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from datetime import date, datetime, timezone
from pathlib import Path

# ── Locate queue dir relative to this script ─────────────────────────────────

_SCRIPT_DIR = Path(__file__).resolve().parent
_DEFAULT_QUEUE = _SCRIPT_DIR.parent / "research-proposals" / "queued"

# ── Import class-router (same directory) ─────────────────────────────────────

sys.path.insert(0, str(_SCRIPT_DIR))
from research_router import route_risk_class, CEO_ALWAYS, CONTRARIAN_GATED, LIGHTWEIGHT  # noqa: E402

# ── Required YAML fields ──────────────────────────────────────────────────────

_REQUIRED = {"title", "hypothesis", "evidence", "target", "risk_class", "proposed_diff_or_brief"}


def _slugify(text: str) -> str:
    """Convert title to a filename-safe slug (lowercase, hyphens, ≤60 chars)."""
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:60]


def _validate(fields: dict) -> list[str]:
    """Return list of validation errors (empty = valid)."""
    errors: list[str] = []

    missing = _REQUIRED - set(fields.keys())
    if missing:
        errors.append(f"Missing required fields: {sorted(missing)}")

    if "title" in fields:
        if not isinstance(fields["title"], str) or not fields["title"].strip():
            errors.append("title must be a non-empty string")
        elif len(fields["title"]) > 120:
            errors.append(f"title too long: {len(fields['title'])} chars (max 120)")

    if "evidence" in fields:
        ev = fields["evidence"]
        if not isinstance(ev, list) or len(ev) == 0:
            errors.append("evidence must be a non-empty list")
        elif not all(isinstance(e, str) and e.strip() for e in ev):
            errors.append("every evidence entry must be a non-empty string")

    for key in ("hypothesis", "target", "proposed_diff_or_brief"):
        if key in fields and (not isinstance(fields[key], str) or not fields[key].strip()):
            errors.append(f"{key} must be a non-empty string")

    return errors


def _render_yaml(fields: dict, gate: str) -> str:
    """Render a minimal hand-crafted YAML block (stdlib only, no PyYAML)."""
    # ponytail: hand-craft YAML for this fixed schema — no yaml dep needed.
    # Upgrade path: import yaml if schema grows complex nested types.
    def _esc(s: str) -> str:
        # Wrap in double-quotes and escape internal quotes/newlines for safety.
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'

    lines = [
        "# Research proposal — generated by research-propose.py",
        "# PROPOSE-ONLY: filing this changes NOTHING live.",
        f"# Gate: {gate}",
        f"# Filed: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
        "",
        f"title: {_esc(fields['title'])}",
        f"hypothesis: {_esc(fields['hypothesis'])}",
        "evidence:",
    ]
    for item in fields["evidence"]:
        lines.append(f"  - {_esc(item)}")
    lines += [
        f"target: {_esc(fields['target'])}",
        f"risk_class: {_esc(fields['risk_class'])}",
        f"gate: {_esc(gate)}",
        f"proposed_diff_or_brief: {_esc(fields['proposed_diff_or_brief'])}",
    ]
    return "\n".join(lines) + "\n"


def write_proposal(
    fields: dict,
    queue_dir: Path | None = None,
    slug: str | None = None,
) -> Path:
    """
    Validate and write a proposal file to queue_dir.
    Raises ValueError with a clear message on validation failure.
    Returns the Path of the written file.
    Never writes a partial file on failure (atomic via tmp+rename).
    """
    errors = _validate(fields)
    if errors:
        raise ValueError("Proposal rejected — validation errors:\n" + "\n".join(f"  - {e}" for e in errors))

    queue_dir = queue_dir or _DEFAULT_QUEUE
    queue_dir = Path(queue_dir)
    queue_dir.mkdir(parents=True, exist_ok=True)

    gate = route_risk_class(fields.get("risk_class"), fields.get("target"))
    content = _render_yaml(fields, gate)

    today = date.today().isoformat()
    file_slug = slug or _slugify(fields["title"])
    filename = f"{today}-{file_slug}.yaml"
    dest = queue_dir / filename

    # ponytail: atomic write via tmp file — prevents partial writes on error.
    tmp = dest.with_suffix(".yaml.tmp")
    try:
        tmp.write_text(content, encoding="utf-8")
        tmp.rename(dest)
    except Exception:
        tmp.unlink(missing_ok=True)
        raise

    return dest


# ── CLI ───────────────────────────────────────────────────────────────────────

def _demo(queue_dir: Path) -> None:
    """Self-check: write a valid proposal + attempt a malformed one."""
    import tempfile

    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_q = Path(tmp_dir) / "queued"

        # Test 1: Valid proposal — should succeed.
        valid = {
            "title": "Add funding-rate feature to ETH strategy",
            "hypothesis": "Funding rate sign predicts 5-min direction on ETH perps.",
            "evidence": [
                "Binance funding rate 2025-01 to 2026-06: neg rate -> UP bias, n=142, WR=56%",
                "strategy/features.py line 42: funding_rate currently unused",
            ],
            "target": "my-project/strategy/features.py",
            "risk_class": "trading-logic",
            "proposed_diff_or_brief": "Add funding_rate as feature[15]; retrain ETH model.",
        }
        dest = write_proposal(valid, queue_dir=tmp_q, slug="eth-funding-rate")
        content = dest.read_text()
        assert "title:" in content, "read-back failed: title missing"
        assert "CEO-ALWAYS" in content, "gate not written (trading-logic should be CEO-ALWAYS)"
        print(f"  [PASS] Valid proposal written: {dest.name}")
        print(f"         Gate: CEO-ALWAYS (trading-logic -> CEO-ALWAYS, correct)")

        # Test 2: Re-derive test — low risk_class but core target.
        low_class_core_target = {
            "title": "Tweak NN wording",
            "hypothesis": "Minor clarification to NN#3 text.",
            "evidence": ["NN#3 wording is ambiguous on model-only changes"],
            "target": "CLAUDE.md",
            "risk_class": "note",  # self-declared low risk
            "proposed_diff_or_brief": "Clarify NN#3 scope.",
        }
        dest2 = write_proposal(low_class_core_target, queue_dir=tmp_q, slug="nn3-clarify")
        content2 = dest2.read_text()
        assert "CEO-ALWAYS" in content2, "re-derive failed: CLAUDE.md target should force CEO-ALWAYS"
        print("  [PASS] Re-derive test: 'note' risk_class + CLAUDE.md target -> CEO-ALWAYS")

        # Test 3: Malformed proposal — must be rejected, zero file written.
        malformed = {
            "title": "",  # empty title
            "hypothesis": "Something",
            "evidence": [],  # empty evidence
            "target": "foo.py",
            "risk_class": "note",
            "proposed_diff_or_brief": "change something",
        }
        rejected = False
        try:
            write_proposal(malformed, queue_dir=tmp_q, slug="bad")
        except ValueError as exc:
            rejected = True
            print(f"  [PASS] Malformed proposal rejected: {exc}")
        assert rejected, "malformed proposal was NOT rejected"
        assert not (tmp_q / f"{date.today().isoformat()}-bad.yaml").exists(), "partial file written"
        print("  [PASS] No partial file written on rejection")

    print()
    print("--demo: ALL PASS")
    sys.exit(0)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Write a validated PROPOSE-only research proposal to the queue."
    )
    parser.add_argument("--title", help="Short label (≤120 chars)")
    parser.add_argument("--hypothesis", help="What we believe and why")
    parser.add_argument("--evidence", nargs="+", metavar="CITATION", help="Evidence items (≥1)")
    parser.add_argument("--target", help="File path or area this would change")
    parser.add_argument("--risk-class", dest="risk_class", help="Self-declared risk class")
    parser.add_argument("--diff", dest="proposed_diff_or_brief", metavar="DIFF", help="Diff or brief")
    parser.add_argument("--slug", default=None, help="Optional filename slug (auto from title if omitted)")
    parser.add_argument(
        "--queue-dir",
        default=str(_DEFAULT_QUEUE),
        help=f"Queue directory (default: {_DEFAULT_QUEUE})",
    )
    parser.add_argument("--demo", action="store_true", help="Run self-check and exit")
    args = parser.parse_args()

    queue_dir = Path(args.queue_dir)

    if args.demo:
        _demo(queue_dir)

    # Require all fields when not in demo mode.
    required_args = ["title", "hypothesis", "evidence", "target", "risk_class", "proposed_diff_or_brief"]
    missing_args = [f"--{a.replace('_', '-')}" for a in required_args if not getattr(args, a)]
    if missing_args:
        parser.error(f"Missing required arguments: {', '.join(missing_args)}")

    fields = {
        "title": args.title,
        "hypothesis": args.hypothesis,
        "evidence": args.evidence,
        "target": args.target,
        "risk_class": args.risk_class,
        "proposed_diff_or_brief": args.proposed_diff_or_brief,
    }

    try:
        dest = write_proposal(fields, queue_dir=queue_dir, slug=args.slug)
        gate = route_risk_class(fields["risk_class"], fields["target"])
        print(f"Proposal filed: {dest}")
        print(f"Gate: {gate}")
        sys.exit(0)
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
